---
- name: Install TFTP Server
  yum: name={{ item }} state=present
  with_items:
    - syslinux
    - tftp
    - tftp-server
    - nginx

- name: Allow TFTP access only for the trusted zone
  firewalld:
    service: tftp
    permanent: yes
    immediate: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
    - lab-internal
    - lab-dmz
    - lab-public
  notify: reload firewalld

- name: Configure the pxelinux.cfg dir
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory

- name: Configure the pxelinux default file
  copy:
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    src: files/var/lib/tftpboot/pxelinux.cfg/default

- name: Configure the pxelinux default file
  copy:
    remote_src: yes
    dest: /var/lib/tftpboot/
    src: "{{ item }}"
  with_items:
    - /usr/share/syslinux/pxelinux.0
    - /usr/share/syslinux/menu.c32
    - /var/ftp/pub/distro/centos/7/images/pxeboot/vmlinuz
    - /var/ftp/pub/distro/centos/7/images/pxeboot/initrd.img

- name: Create the Kickstart dir
  file:
    path: /var/ftp/kickstart
    state: directory
    mode: 0755

- name: Prepare the Kickstart file (ftp)
  template:
    src: templates/centos7-ks-ftp.cfg.j2
    dest: /var/ftp/kickstart/centos7-ks-ftp.cfg
    mode: 0444

- name: Prepare the Kickstart file (cdrom)
  template:
    src: templates/centos7-ks-cd.cfg.j2
    dest: /var/ftp/kickstart/centos7-ks-cd.cfg
    mode: 0444

- name: Start and enable the TFTP Socket
  service:
    name: tftp.socket
    state: started
    enabled: yes
