---
- hosts: localhost
  connection: local

  vars_files:
    - vars.yml

  tasks:
    - name: Delete all host-only interfaces
      shell: "VBoxManage list hostonlyifs|grep ^Name:|tr -s ' '|cut -d ' ' -f2|xargs -I{} VBoxManage hostonlyif remove {}"
    