---
- hosts: localhost
  connection: local
  gather_facts: no
  
  vars_files:
    - vars.yml

  tasks:
    - name: Start the VM if it exists
      shell: |
        vm_exists=$(VBoxManage list vms | grep "{{ vm_name }}" | cut -f 1 -d " "| tr -d '"')
        if [ "$vm_exists" == "{{ vm_name }}" ]; then
            VBoxManage startvm {{ vm_name }}
        else
          echo VM not found: {{ vm_name }}
          exit 1
        fi
