---
- hosts: localhost
  connection: local

  vars_files:
    - ~/.ansible-vaults/lab.yml
    - vars.yml

  vars:
    - ansible_user_pub_key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
    - vm_name: router

  tasks:
    - name: Configure the Router's kickstart file
      template:
        src: "templates/centos-ks-router.cfg.j2"
        dest: "http/kickstart/centos-ks-router.cfg"

    - name: Start the web server to be used by NAT-based VMs to PXE boot
      shell: |
        if [ "$(lsof -i -P -n | grep "TCP \*:8000 (LISTEN)"|cut -c 11-14)" == "" ]; then
            $(cd http && python -m http.server > webserver.log)&
        fi
    
    - name: Make sure the VM doesn't already exist
      shell: |
        vm_exists=$(VBoxManage list vms | grep '"{{ vm_name }}"' | cut -f 1 -d " ")
        if [ "$vm_exists" != "" ];then 
          echo A VM named {{ vm_name }} already exists
          exit 1
        fi

    - name: Configure the VM Base
      command: |
        scripts/config-vm-base.sh {{ vm_name }} lab
    
    - name: Configure the VM specifics
      command: |
        scripts/config-router.sh {{ vm_name }}

    - name: Attach a hard drive
      command: |
        scripts/attach-hdd.sh {{ vm_name }} "{{ vbox_disk_path }}"

    - name: Attach the install ISO
      command: |
        scripts/attach-installdvd.sh {{ vm_name }} "{{ vm_iso_path }}"