---
- hosts: all
  become: yes

  tasks:

    - import_tasks: tasks-base.yml

    - name: Remove packages we do not need
      yum: name={{ item }} state=removed
      with_items:
        - NetworkManager

