---
#- name: Configure the EPEL repo
#  yum: name=epel-release state=present
  
- name: Make sure we have the packages we need
  yum: name={{ item }} state=present
  with_items:
    - bash-completion
    - net-tools
    - nmap

- name: Remove packages we do not need
  yum: name={{ item }} state=removed
  with_items:
    - NetworkManager
