---
all:
  vars:
    ansible_user: ansible
    ansible_become: yes
    ansible_ssh_private_key_file: ~/.ssh/ansible
    ansible_ssh_public_key_file: ~/.ssh/ansible.pub
    
  hosts:
    router:
      ansible_host: router
    canary-internal:
      ansible_host: 172.16.1.50
    canary-dmz:
      ansible_host: 172.16.100.50