---
- hosts: router
  tasks:
    - hostname:
        name: router.lab.example.com
    - import_role:
        name: router
    - import_role:
        name: dhcp-server
    - import_role:
        name: dns-server
