--- 
#- import_tasks: network.yml
- import_tasks: firewall.yml
- import_tasks: time.yml
- import_tasks: squid.yml

# Configure routing

- name: Setup sysctl
  lineinfile:
    dest: /etc/sysctl.d/99-sysctl.conf
    regexp: '^net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward = 1'
  notify: reload sysctl

    
    
