---
- name: Install Squid
  yum: name={{ item }} state=present
  with_items:
    - squid
    - httpd

- name: Configure squid
  copy:
    src: files/etc/squid/squid.conf
    dest: /etc/squid/squid.conf
    owner: root
    group: squid
    mode: 0640
  notify: "restart squid"

- name: Configure Squid cache_dir
  file:
    path: /var/spool/squid
    owner: root
    group: squid
    mode: 0775
    state: directory

- name: Configure the Firewall for Squid
  firewalld:
    service: squid
    permanent: yes
    immediate: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
    - lab-internal
    - lab-dmz
    - lab-public
  notify: reload firewalld

- name: Configure the Firewall for Squid HTTP
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
    - lab-internal
    - lab-dmz
    - lab-public
  notify: reload firewalld

- name: Start and enable Squid
  service:
    name: squid
    state: started
    enabled: yes