---
- name: Allow NTP Inbound only for the lab-internal zone
  firewalld:
    service: ntp
    permanent: yes
    immediate: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
    - lab-internal
    - lab-dmz
    - lab-public
  notify: reload firewalld

- name: Let chrony server others
  lineinfile:
    path: /etc/chrony.conf
    line: 'allow 172.16.0.0/16'
  notify: restart chronyd
