---
- name: Remove ntp
  yum: 
    name: ntp
    state: absent

- name: Install chrony
  yum: 
    name: chrony
    state: present
  
- name: Enable the service
  service:
    name: chronyd
    enabled: yes
    state: started
