---
- name: Ensure sshd service is enabled and running
  service:
    name: sshd
    enabled: yes
    state: started

- name: Ensure fail2ban service is enabled and running
  service:
    name: fail2ban
    enabled: yes
    state: started

- name: Ensure firewalld is enabled and running
  service:
    name: firewalld
    enabled: yes
    state: started
    