---
- name: Make sure SSH server is installed
  yum:
    name: openssh-server
    state: present

- name: Ensure sshd service is enabled and running
  service:
    name: sshd
    enabled: yes
    state: started

- name: Copy over the SSHD configuration
  copy:
    src: "{{ role_path }}/files/etc/ssh/sshd_config"
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: 0644
    backup: yes
  notify: restart sshd
