---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart chronyd
  service:
    name: chronyd
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: reload firewalld
  command: firewall-cmd --reload

- name: reload sysctl
  command: sysctl -p

- name: restart squid
  service:
    name: squid
    state: restarted
    